spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    #  routes:
    #    - id: rota_course
    #      uri: lb://course/
    #      predicates:
    #        - Path=/v1/admin/course/**

server:
  port: 8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
